import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import contract from './contract/request-dtos.json';

/**
 * The hand-written request types, checked against the backend's own DTOs.
 *
 * <p>The bug this exists for: V135 added `boolean materialRefund` to the backend's
 * `PaymentReceiptRequest`. Nothing told this repository. `types.ts` is written BY HAND, so its
 * interface never grew the field, TypeScript stayed perfectly happy — and recording a payment
 * answered «Некоректний формат запиту» for weeks. No test on either side could see it: the
 * backend's service tests build the record in Java (Jackson never runs), ours mock `@/api/*` (the
 * body is never serialized), and nothing at all read both sides.</p>
 *
 * <p>`contract/request-dtos.json` is generated by the backend's `RequestContractSnapshotTest` and
 * copied here. Changing a request DTO reddens THAT test, which names this file; this one then
 * checks that the interfaces actually agree. Between them the two repos can no longer drift in
 * silence.</p>
 *
 * <p><b>The rules are deliberately asymmetric.</b> A field WE declare must exist on the backend —
 * otherwise we are sending something nothing reads, or the name was changed under us. A field the
 * backend REQUIRES must be declared here and non-optional — that is a save that 400s. A field the
 * backend merely accepts may be left out of the interface: plenty of endpoints have options this
 * app has no screen for, and demanding them would make this guard cry wolf until someone deletes
 * it.</p>
 */
const TYPES = join(process.cwd(), 'src/api/types.ts');
const SNAPSHOT = 'src/test/resources/contract/request-dtos.json';

type Field = { type: string; optional: boolean };

const source = readFileSync(TYPES, 'utf8');

/** `export type Foo = 'A' | 'B';` — the string-literal unions our enums cross the wire as. */
const aliases = new Map<string, string>(
  [...source.matchAll(/export type (\w+)\s*=\s*([^;]+);/g)].map((m) => [m[1], m[2]]),
);

function coarse(raw: string): string {
  const t = raw.replace(/\|\s*null/g, '').replace(/\|\s*undefined/g, '').trim();
  if (/\[\]$/.test(t) || /^Array</.test(t)) return 'array';
  if (t === 'string' || t === 'number' || t === 'boolean') return t;
  if (t.includes("'")) return 'string';
  const alias = aliases.get(t);
  return alias === undefined ? 'object' : coarse(alias);
}

/** Brace-counting rather than a regex: a few interfaces carry an inline object member. */
function interfaces(): Map<string, Map<string, Field>> {
  const found = new Map<string, Map<string, Field>>();
  const header = /export interface (\w+Request)\s*\{/g;
  for (let m = header.exec(source); m !== null; m = header.exec(source)) {
    let depth = 1;
    let i = m.index + m[0].length;
    for (; i < source.length && depth > 0; i++) {
      if (source[i] === '{') depth++;
      else if (source[i] === '}') depth--;
    }
    found.set(m[1], members(source.slice(m.index + m[0].length, i - 1)));
  }
  return found;
}

function members(body: string): Map<string, Field> {
  const clean = body.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
  const fields = new Map<string, Field>();
  // Top level only — a nested object member's own fields are not part of this contract.
  let depth = 0;
  for (const line of clean.split('\n')) {
    const before = depth;
    depth += (line.match(/\{/g) ?? []).length - (line.match(/\}/g) ?? []).length;
    const m = /^\s*(\w+)(\??):\s*(.+?);?\s*$/.exec(line);
    if (m !== null && before === 0) fields.set(m[1], { type: coarse(m[3]), optional: m[2] === '?' });
  }
  return fields;
}

const declared = interfaces();
const shared = [...declared.keys()].filter((name) => name in contract).sort();

describe('the request contract with the backend', () => {
  it('reaches the interfaces it is meant to guard', () => {
    // A guard that matches nothing passes forever. Name the one this was written for.
    expect(shared).toContain('PaymentReceiptRequest');
    expect(shared.length).toBeGreaterThan(20);
  });

  it.each(shared)('%s declares nothing the backend does not have', (name) => {
    const backend = contract[name as keyof typeof contract] as Record<string, string>;
    const unknown = [...declared.get(name)!.keys()].filter((f) => !(f in backend));
    expect(unknown, `${name} sends fields the backend DTO has no component for`).toEqual([]);
  });

  it.each(shared)('%s declares every field the backend requires', (name) => {
    const backend = contract[name as keyof typeof contract] as Record<string, string>;
    const ours = declared.get(name)!;
    const missing = Object.entries(backend)
      .filter(([, spec]) => !spec.endsWith('?'))
      .map(([field]) => field)
      .filter((field) => ours.get(field) === undefined || ours.get(field)!.optional);
    expect(missing, `${name}: the backend rejects a body without these`).toEqual([]);
  });

  it.each(shared)('%s agrees with the backend on types', (name) => {
    const backend = contract[name as keyof typeof contract] as Record<string, string>;
    const wrong = [...declared.get(name)!.entries()]
      .filter(([field]) => field in backend)
      .filter(([, ours]) => ours.type !== 'object')
      .filter(([field, ours]) => ours.type !== backend[field].replace(/\?$/, ''))
      .map(([field, ours]) => `${field}: ours ${ours.type}, backend ${backend[field]}`);
    expect(wrong, `${name} disagrees about field types`).toEqual([]);
  });

  /**
   * The copy above is only as good as the last time someone copied it. This repo's CI has no
   * backend checkout and cannot tell — but the machine every push is made from does, so the one
   * place staleness matters is covered. Absent sibling: nothing to compare, and that is not a
   * failure.
   */
  it('matches the live backend snapshot when the sibling repo is present', () => {
    const live = join(process.cwd(), '..', 'majstr-backend', SNAPSHOT);
    if (!existsSync(live)) return;
    expect(
      readFileSync(join(process.cwd(), 'src/api/contract/request-dtos.json'), 'utf8').trim(),
      `stale copy — refresh it from ../majstr-backend/${SNAPSHOT}`,
    ).toBe(readFileSync(live, 'utf8').trim());
  });
});
