import { describe, it, expect } from 'vitest';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import contract from './contract/request-dtos.json';

/**
 * The hand-written request types, checked against the backend's own DTOs.
 *
 * <p>The bug this exists for: V135 added `boolean materialRefund` to the backend's
 * `PaymentReceiptRequest`. Nothing told this repository. `types.ts` is written BY HAND, so its
 * interface never grew the field, TypeScript stayed perfectly happy — and recording a payment
 * answered «Некоректний формат запиту» for weeks. No test on either side could see it: the
 * backend's service tests build the record in Java (Jackson never runs), ours mock `@/api/*` (the
 * body is never serialized), and nothing at all read both sides.</p>
 *
 * <p>`contract/request-dtos.json` is generated by the backend's `RequestContractSnapshotTest` and
 * copied here. Changing a request DTO reddens THAT test, which names this file; this one then
 * checks that the interfaces actually agree. Between them the two repos can no longer drift in
 * silence.</p>
 *
 * <p><b>The rules are deliberately asymmetric.</b> A field WE declare must exist on the backend —
 * otherwise we are sending something nothing reads, or the name was changed under us. A field the
 * backend REQUIRES must be declared here and non-optional — that is a save that 400s. A field the
 * backend merely accepts may be left out of the interface: plenty of endpoints have options this
 * app has no screen for, and demanding them would make this guard cry wolf until someone deletes
 * it.</p>
 */
const TYPES = join(process.cwd(), 'src/api/types.ts');
const SNAPSHOT = 'src/test/resources/contract/request-dtos.json';

type Field = { type: string; optional: boolean };

const source = readFileSync(TYPES, 'utf8');

/** `export type Foo = 'A' | 'B';` — the string-literal unions our enums cross the wire as. */
const aliases = new Map<string, string>(
  [...source.matchAll(/export type (\w+)\s*=\s*([^;]+);/g)].map((m) => [m[1], m[2]]),
);

function coarse(raw: string): string {
  const t = raw.replace(/\|\s*null/g, '').replace(/\|\s*undefined/g, '').trim();
  if (/\[\]$/.test(t) || /^Array</.test(t)) return 'array';
  if (t === 'string' || t === 'number' || t === 'boolean') return t;
  if (t.includes("'")) return 'string';
  const alias = aliases.get(t);
  return alias === undefined ? 'object' : coarse(alias);
}

/**
 * Brace-counting rather than a regex: a few interfaces carry an inline object member.
 *
 * <p>`extends` is part of the header (review P-30). Without it `WorkActUpdateRequest extends
 * WorkActCreateRequest` was simply not found, so the DTO the act editor PATCHes with — the one
 * carrying every money field on the document — was outside the contract entirely. An inherited
 * field counts as declared: that is what `extends` means on the wire.</p>
 */
function interfaces(): Map<string, Map<string, Field>> {
  const own = new Map<string, Map<string, Field>>();
  const bases = new Map<string, string>();
  const header = /export interface (\w+Request)(?:\s+extends\s+([\w\s,]+?))?\s*\{/g;
  for (let m = header.exec(source); m !== null; m = header.exec(source)) {
    let depth = 1;
    let i = m.index + m[0].length;
    for (; i < source.length && depth > 0; i++) {
      if (source[i] === '{') depth++;
      else if (source[i] === '}') depth--;
    }
    own.set(m[1], members(source.slice(m.index + m[0].length, i - 1)));
    if (m[2] !== undefined) bases.set(m[1], m[2].trim());
  }
  const found = new Map<string, Map<string, Field>>();
  for (const [name, fields] of own) {
    const merged = new Map<string, Field>();
    for (const base of (bases.get(name) ?? '').split(',').map((b) => b.trim()).filter(Boolean)) {
      for (const [field, spec] of own.get(base) ?? []) merged.set(field, spec);
    }
    for (const [field, spec] of fields) merged.set(field, spec);
    found.set(name, merged);
  }
  return found;
}

function members(body: string): Map<string, Field> {
  const clean = body.replace(/\/\*[\s\S]*?\*\//g, '').replace(/\/\/[^\n]*/g, '');
  const fields = new Map<string, Field>();
  // Top level only — a nested object member's own fields are not part of this contract.
  let depth = 0;
  for (const line of clean.split('\n')) {
    const before = depth;
    depth += (line.match(/\{/g) ?? []).length - (line.match(/\}/g) ?? []).length;
    const m = /^\s*(\w+)(\??):\s*(.+?);?\s*$/.exec(line);
    // `foo: string | null` is NOT a field the backend can require (review P-30): TypeScript calls
    // it mandatory, and the value it makes mandatory is a `null` a `@NotNull` component refuses.
    // So nullable counts as optional here, which is the question this contract actually asks.
    if (m !== null && before === 0) {
      // Asked of the TOP-LEVEL type only: `items: { id: string; category?: string | null }[]` is
      // not a nullable field, it is an array whose ELEMENT has one.
      const bare = m[3].replace(/\{[^}]*\}/g, 'object');
      fields.set(m[1], {
        type: coarse(m[3]),
        optional: m[2] === '?' || /\|\s*null\b/.test(bare),
      });
    }
  }
  return fields;
}

const declared = interfaces();
// A dotted key — «ApplyTemplatesRequest.TemplatePick» — is a NESTED backend record, recorded by the
// snapshot since review B-46 so a required field added to one reddens the backend's own test. This
// reader matches top-level request types by name, so those entries are simply not among `shared`;
// checking them here would need a name map from each nested record to the interface we call it, and
// the drift they exist to catch is already caught one repo over.
/**
 * What the backend calls an interface we name differently.
 *
 * <p>A NESTED backend record is keyed `Parent.Nested` in the snapshot (review B-46), and this repo
 * flattens those into their own interfaces — `TemplatePickRequest` is `ApplyTemplatesRequest`'s own
 * `TemplatePick`. One line each, so the nested record is compared here too instead of being skipped
 * for having an unfamiliar name (review P-30).</p>
 */
const BACKEND_NAME: Record<string, string> = {
  TemplatePickRequest: 'ApplyTemplatesRequest.TemplatePick',
};

/** The snapshot key for one of our interfaces, or undefined when the backend has no such DTO. */
const keyOf = (name: string): string | undefined => {
  const mapped = BACKEND_NAME[name] ?? name;
  return mapped in contract ? mapped : undefined;
};

const shared = [...declared.keys()].filter((name) => keyOf(name) !== undefined).sort();

/**
 * Every `*Request` type the API LAYER mentions — these are the bodies this app really sends.
 *
 * <p>The contract used to compare whatever happened to match by name, which is a different and
 * weaker question (review P-30): a DTO the app posts under a name the snapshot spells differently
 * was simply skipped, silently, and that is precisely the drift the file exists to catch. A
 * backend DTO with no caller HERE is not a problem — plenty of endpoints have options this app has
 * no screen for — so the coverage is asked from our side, not from the snapshot's.</p>
 */
const apiDir = join(process.cwd(), 'src/api');
const posted = new Set<string>();
for (const file of readdirSync(apiDir)) {
  if (!file.endsWith('.ts') || file.endsWith('.test.ts') || file === 'types.ts') continue;
  for (const [, name] of readFileSync(join(apiDir, file), 'utf8').matchAll(/\b(\w+Request)\b/g)) {
    posted.add(name);
  }
}

describe('the request contract with the backend', () => {
  it('reaches the interfaces it is meant to guard', () => {
    // A guard that matches nothing passes forever. Name the one this was written for.
    expect(shared).toContain('PaymentReceiptRequest');
    expect(shared.length).toBeGreaterThan(20);
    // And the DTO whose header the old regex could not read at all.
    expect(shared).toContain('WorkActUpdateRequest');
  });

  it('covers every request body the api layer actually sends', () => {
    const uncovered = [...posted]
      .filter((name) => declared.has(name))
      .filter((name) => keyOf(name) === undefined)
      .sort();
    expect(
      uncovered,
      'these are sent by src/api but absent from the backend snapshot — renamed, or removed',
    ).toEqual([]);
  });

  it.each(shared)('%s declares nothing the backend does not have', (name) => {
    const backend = contract[keyOf(name) as keyof typeof contract] as Record<string, string>;
    const unknown = [...declared.get(name)!.keys()].filter((f) => !(f in backend));
    expect(unknown, `${name} sends fields the backend DTO has no component for`).toEqual([]);
  });

  it.each(shared)('%s declares every field the backend requires', (name) => {
    const backend = contract[keyOf(name) as keyof typeof contract] as Record<string, string>;
    const ours = declared.get(name)!;
    const missing = Object.entries(backend)
      .filter(([, spec]) => !spec.endsWith('?'))
      .map(([field]) => field)
      .filter((field) => ours.get(field) === undefined || ours.get(field)!.optional);
    expect(missing, `${name}: the backend rejects a body without these`).toEqual([]);
  });

  it.each(shared)('%s agrees with the backend on types', (name) => {
    const backend = contract[keyOf(name) as keyof typeof contract] as Record<string, string>;
    const wrong = [...declared.get(name)!.entries()]
      .filter(([field]) => field in backend)
      .filter(([, ours]) => ours.type !== 'object')
      .filter(([field, ours]) => ours.type !== backend[field].replace(/\?$/, ''))
      .map(([field, ours]) => `${field}: ours ${ours.type}, backend ${backend[field]}`);
    expect(wrong, `${name} disagrees about field types`).toEqual([]);
  });

  /**
   * The copy above is only as good as the last time someone copied it. This repo's CI has no
   * backend checkout and cannot tell — but the machine every push is made from does, so the one
   * place staleness matters is covered. Absent sibling: nothing to compare, and that is not a
   * failure.
   */
  it('matches the live backend snapshot when the sibling repo is present', () => {
    // `MAJSTR_BACKEND_DIR` for a checkout that is not the sibling `../majstr-backend` (review
    // P-30), and a WARNING rather than silence when neither is there: a staleness check that can
    // skip itself without saying so is a check nobody knows they lost.
    const root = process.env.MAJSTR_BACKEND_DIR ?? join(process.cwd(), '..', 'majstr-backend');
    const live = join(root, SNAPSHOT);
    if (!existsSync(live)) {
      console.warn(
        `[contract] no backend checkout at ${root} — the copy's freshness was NOT verified.`
        + ' Set MAJSTR_BACKEND_DIR to point at one.',
      );
      return;
    }
    // Line endings normalised on BOTH sides (review B-36): the backend BUILDS this file with LF,
    // and with core.autocrlf a Windows checkout of either repo hands back CRLF — so a byte-for-byte
    // comparison could never hold, and it passed only where a run had just rewritten the file.
    const lf = (text: string) =>
      text.replace(/\r\n/g, '\n').replace(/\r/g, '\n').trim();
    expect(
      lf(readFileSync(join(process.cwd(), 'src/api/contract/request-dtos.json'), 'utf8')),
      `stale copy — refresh it from ../majstr-backend/${SNAPSHOT}`,
    ).toBe(lf(readFileSync(live, 'utf8')));
  });
});
